%global srcname vorta
%global debug_package %{nil}

Name:           %{srcname}
Version:        0.8.7
Release:        1%{?dist}
Summary:        A GUI for Borg Backup
License:        GPLv3
URL:            https://vorta.borgbase.com/
Source0:        https://github.com/borgbase/vorta/archive/v%{version}.tar.gz

Requires:       python3-appdirs
Requires:       python3-paramiko
Requires:       python3-peewee
Requires:       python3-dateutil
Requires:       python3-qt5
Requires:       python3-APScheduler
Requires:       python3-psutil
Requires:       python3-secretstorage
Requires:       borgbackup

BuildArch:      noarch
BuildRequires:  python3-devel
BuildRequires:  python3-setuptools
BuildRequires:  python3-pip
BuildRequires:  python3-wheel
BuildRequires:  python-rpm-macros

# opensuse compatibility layer taken from copr taw/element
%if 0%{?suse_version:1}
# https://en.opensuse.org/openSUSE:Build_Service_cross_distribution_howto
#BuildRequires: libappstream-glib8 appstream-glib
BuildRequires: ca-certificates-cacert ca-certificates-mozilla ca-certificates
%if 0%{?sle_version}
# Leap
# provides libcrypto.so.1
BuildRequires: libopenssl1_0_0
%if 0%{?sle_version} == 150100
# Leap 15.1
%endif
%if 0%{?sle_version} == 150200
# Leap 15.2
%endif
%else
# Tumbleweed
# provides libcrypto.so.1
BuildRequires: libcrypt1
%endif
%else
# not opensuse
%endif

%description
Vorta is a backup client for macOS and Linux desktops. 
It integrates the mighty BorgBackup with your desktop environment 
to protect your data from disk failure, ransomware and theft

%prep

%autosetup -n %{srcname}-%{version}

# Cython is too old in RHEL8.0
%{!?el8:rm -f $(grep -rl '/\* Generated by Cython')}

%build
%py3_build

%install
%py3_install
install -D %{_builddir}/%{srcname}-%{version}/build/lib/vorta/assets/icons/icon.svg %{buildroot}%{_datadir}/icons/hicolor/scalable/apps/com.borgbase.Vorta.svg
install -D %{_builddir}/%{srcname}-%{version}/package/icon-symbolic.svg %{buildroot}%{_datadir}/icons/hicolor/symbolic/apps/com.borgbase.Vorta-symbolic.svg
install -D %{_builddir}/%{srcname}-%{version}/src/vorta/assets/metadata/com.borgbase.Vorta.desktop %{buildroot}%{_datadir}/applications/com.borgbase.Vorta.desktop


%files
#%doc RELEASE.md
#%license LICENSE
%{python3_sitelib}/*
%{_bindir}/vorta
%{_datadir}/*

%changelog
* Fri Feb 19 2021 Guilherme Cardoso <gjc@ua.pt> 0.7.3-1
- Improve build dependencies for OpenSuse buildroots
- Relax a little on distribution packages needed for building

* Sun Jan 31 2021 Guilherme Cardoso <gjc@ua.pt> 0.7.2-1
- Fix vorta icon.svg source path
- Add missing buildrequires: python3-pip and python3-setuptools_git

* Sat Jan 2 2021 Guilherme Cardoso <gjc@ua.pt> 0.7.1-1
- Initial release
